### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by RomeoDavide91** [dami1411/angular_tirocinio#1]
Bisogna rendere funzionante il routing

• Aggiungere una nuova pagina "user settings" e aggiungerla come rotta al app.routing.module
    - Fare in modo che cliccando sul link "Pagina 1" l'utente venga ridirezionato sulla pagina creata
    - Quando viene caricata una nuova rotta, il link di riferimento deve essere evidenziato 
• Creare una pagina di atterraggio per i casi 404
    - In caso di 404 l'utente deve essere spedito su un'altra pagina
• Aggiungere una nuova guard
    - Gli utenti no-user e guest non possono accedere alla pagina di gestione utenti
    - La guard deve essere in grado di ridirezionarli su una pagina di cortesia

**Comment by dami1411** [comment]
Task completata, vedi commit fatto in questi minuti
