### ISSUE TITLE
ECommerce

### ISSUE THREAD

**Issue by RomeoDavide91** [dami1411/angular_tirocinio#3]
Bisogna creare una pagina di "prodotti".

- Questa deve mostrare una lista di card contenente un articolo con le seguenti informazioni:
    • Titolo (massimo 32 caratteri)
    • Descrizione (nella preview, in caso di caratteri superiori a 64, deve essere troncata)
    • Immagine di sfondo
    • Pulsante per dettaglio
    • Pulsante per inserimento alla wishlist

- Creare la pagina di dettaglio:
    • Al click del redirect a dettaglio si deve aprire una nuova pagina la cui rotta deve essere parlante (es: home/hdmi-cable)
    • Titolo: in alto a destra
    • L'immagine: a sinistra e al click si deve ingrandire a schermo intero
    • Descrizione: al centro sotto immagine e titolo

- Creare funzionalità wishlist

**Comment by dami1411** [comment]
task completata, vedi stesso commit della issue #1
